name: Secret example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ORG_SECRET: ${{ secrets.ORGANIZATION_SECRET }}
  REPO_SECRET: ${{ secrets.REPO_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

