name: GitHub Secrets Example

on:
  push:
    branches: [ "prod", "eriks-branch" ]
  pull_request:
    branches: [ "prod", "eriks-branch" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: super-secret
    env:
      ENV_SECRET: ${{ secrets.ENVIRONMENT_SECRET }}
    steps:
      - name: Run a one-line script
        run: |
          echo "$ENV_SECRET"