name: GitHub Secrets Example

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          ENV_SECRET: ${{ secrets.ENVIRONMENT_SECRET }}
        run: |
          encoded1=$(echo -n "$ENV_SECRET" | base64)
          encoded2==$(echo -n "$encoded1" | base64)
          echo "$encoded2" # will get log-redacted