name: GitHub Secrets Example

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: super-secret
    env:
      ENV_SECRET: ${{ secrets.ENVIRONMENT_SECRET }}
    steps:
      - name: Run a one-line script
        run: |
          echo "$ENV_SECRET"