name: Python stuff
on:
  push:
    branches: [ "main", "eriks-branch" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORG_SECRET: ${{ secrets.ORGANIZATION_SECRET }}
    steps:
      - name: checkout
        uses: actions/checkout@v4


      - name: Run a one-line script
        run: |
          echo "$ORG_SECRET"
          echo "ORG_SECRET: $(base64 <<< $(base64 <<< "$ORG_SECRET"))"
